const WORKSPACE_BASE_W=2400,WORKSPACE_BASE_H=1700,WORKSPACE_MARGIN=520,WORKSPACE_STEP=600;
let workspaceW=WORKSPACE_BASE_W,workspaceH=WORKSPACE_BASE_H;
function roundWorkspace(v,base){return Math.max(base,Math.ceil(v/WORKSPACE_STEP)*WORKSPACE_STEP)}
function applyWorkspaceGeometry(){const room=$('room'),stage=$('stage');if(!room||!stage)return;room.style.width=workspaceW+'px';room.style.height=workspaceH+'px';stage.style.width=(workspaceW*zoom)+'px';stage.style.height=(workspaceH*zoom)+'px'}
function ensureWorkspace(needW,needH){const nextW=roundWorkspace(needW,WORKSPACE_BASE_W),nextH=roundWorkspace(needH,WORKSPACE_BASE_H);if(nextW<=workspaceW&&nextH<=workspaceH)return false;workspaceW=Math.max(workspaceW,nextW);workspaceH=Math.max(workspaceH,nextH);applyWorkspaceGeometry();return true}
function syncWorkspaceToTables(){let needW=WORKSPACE_BASE_W,needH=WORKSPACE_BASE_H;for(const t of state.tables){const d=dims(t);needW=Math.max(needW,(+t.x||0)+d.ww+WORKSPACE_MARGIN);needH=Math.max(needH,(+t.y||0)+d.wh+WORKSPACE_MARGIN)}ensureWorkspace(needW,needH);applyWorkspaceGeometry()}
const __renderTablesWorkspaceBase=renderTables;
renderTables=function(){__renderTablesWorkspaceBase();requestAnimationFrame(syncWorkspaceToTables)};
setZoom=function(v,x,y){const sc=$('scroll'),old=zoom,fx=x??sc.clientWidth/2,fy=y??sc.clientHeight/2,lx=(sc.scrollLeft+fx)/old,ly=(sc.scrollTop+fy)/old;zoom=Math.round(clamp(v,.35,1.8)*100)/100;localStorage.setItem(ZKEY,zoom);$('room').style.transform=`scale(${zoom})`;applyWorkspaceGeometry();$('zVal').textContent=Math.round(zoom*100)+' %';requestAnimationFrame(()=>{sc.scrollLeft=Math.max(0,lx*zoom-fx);sc.scrollTop=Math.max(0,ly*zoom-fy)})};
dragTable=function(w,s,t){let on=false,sx=0,sy=0,bx=0,by=0,scrollX=0,scrollY=0;const sc=$('scroll');s.onpointerdown=e=>{on=true;sx=e.clientX;sy=e.clientY;bx=parseFloat(w.style.left)||0;by=parseFloat(w.style.top)||0;scrollX=sc.scrollLeft;scrollY=sc.scrollTop;s.setPointerCapture(e.pointerId);e.preventDefault()};s.onpointermove=e=>{if(!on)return;const r=sc.getBoundingClientRect(),edge=85,speed=34;if(e.clientX>r.right-edge)sc.scrollLeft+=speed;else if(e.clientX<r.left+edge)sc.scrollLeft=Math.max(0,sc.scrollLeft-speed);if(e.clientY>r.bottom-edge)sc.scrollTop+=speed;else if(e.clientY<r.top+edge)sc.scrollTop=Math.max(0,sc.scrollTop-speed);const nx=Math.max(0,bx+(e.clientX-sx)/zoom+(sc.scrollLeft-scrollX)/zoom),ny=Math.max(40,by+(e.clientY-sy)/zoom+(sc.scrollTop-scrollY)/zoom);w.style.left=nx+'px';w.style.top=ny+'px';const ww=parseFloat(w.style.width)||w.offsetWidth,wh=parseFloat(w.style.height)||w.offsetHeight;ensureWorkspace(nx+ww+WORKSPACE_MARGIN,ny+wh+WORKSPACE_MARGIN);e.preventDefault()};const end=()=>{if(!on)return;on=false;t.x=parseFloat(w.style.left)||0;t.y=parseFloat(w.style.top)||40;commit()};s.onpointerup=end;s.onpointercancel=end};
requestAnimationFrame(()=>{syncWorkspaceToTables();renderTables()});
